name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  SECRET_KEY: ${{secrets.SECRET_KEY}}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code formatting with Black
        run: black --check .

      - name: Run mypy for type checking
        run: mypy .

      - name: Run tests with pytest
        run: pytest
